### PR TITLE
homework 3

### PR DESCRIPTION
**Pull request by Zoro20171002**

### CODE REVIEW

**Comment by HugoLhuillier** [comment]
hey @Zoro20171002. once again, you removed too many files. next time, could you try to only pull request your solution to the homework? if you're not sure how to do it, we can discuss that in class!

**Comment by HugoLhuillier** [comment]
eventually, you didn't add or remove any file, so that's good. but it's just cleaner if you only modify your file 😉

**Comment by Zoro20171002** [comment]
What I always do is to clone your repo into my computer. However, what happened was that After I finish my homework, I could not push this to my cloud repo. So I try to fork first, then clone from my own cloud repo. But "fork" does not work.

**Comment by HugoLhuillier** [comment]
that's indeed not the best way to do it. i'll show you the proper way at the beginning / end of today's class.

**Pull request merged**
